# File: .github/workflows/ci.yml

name: Node.js CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build_and_test:
    name: Build and Test # Nama ini mungkin muncul di GitHub Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Gunakan versi Node yang stabil dan sesuai proyek Anda

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint # Pastikan skrip ini ada dan bekerja

      - name: Run tests
        run: npm test -- --watchAll=false # Menjalankan Jest tests

      - name: Build application
        run: npm run build